server:
  port: 8090

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /openapi-ui-exchange-rate.html

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: giancarlo
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always

exchange-rate:
  error:
    exchange-rate-not-found: Tipo de cambio no encontrado
    exchange-rate-error-server: Ocurrio un error en el servidor
